---
title: "Untitled"
author: "Justin De Burgo, Sherief El-Ghazawi"
date: "5/14/2020"
output: html_document
---



```{r setup, include=TRUE}
library(tidyverse)
```

## R Markdown


```{r nba_seasons, inlciude=TRUE}
nba_seasons <- read_csv("NBA_Season_Data.csv")
nba_seasons1 <- nba_seasons%>%
                filter(Year >= 2000) 
nba_seasons1
distinct(nba_seasons1, Tm)
```




```{r nba_finals_mvp}
nba_finals_mvp <- read_csv("NBA_Finals_and_MVP.csv")
nba_finals_mvp <- nba_finals_mvp%>%
                filter(Year >= 2000) 
for (row in 1:nrow(nba_finals_mvp)) {
  
 if (nba_finals_mvp[row, "NBA Champion"] == "Los Angeles Lakers") {
   nba_finals_mvp[row, "NBA Champion"] <- "LAL"
 }
  
  if (nba_finals_mvp[row, "NBA Champion"] == "Golden State Warriors") {
   nba_finals_mvp[row, "NBA Champion"] <- "GSW"
  }
  
  if ( nba_finals_mvp[row, "NBA Champion"] == "Cleveland Cavaliers") {
   nba_finals_mvp[row, "NBA Champion"] <- "CLE"
  }
  
  if (nba_finals_mvp[row, "NBA Champion"] == "San Antonio Spurs") {
   nba_finals_mvp[row, "NBA Champion"] <- "SAS"
  }
  
  
  if ( nba_finals_mvp[row, "NBA Champion"] == "Miami Heat") {
   nba_finals_mvp[row, "NBA Champion"] <- "MIA"
  }
  
  if (nba_finals_mvp[row, "NBA Champion"] == "Dallas Mavericks") {
   nba_finals_mvp[row, "NBA Champion"] <- "DAL"
  }
  
  if (nba_finals_mvp[row, "NBA Champion"] == "Boston Celtics") {
   nba_finals_mvp[row, "NBA Champion"] <- "BOS"
  }
  
  if (nba_finals_mvp[row, "NBA Champion"] == "Detroit Pistons") {
   nba_finals_mvp[row, "NBA Champion"] <- "DET"
  }
  
}
```


```{r nba_performances, include=TRUE}
nba_performance <- read_csv("Historical_NBA_Performance.csv")
nba_performance <- nba_performance%>%
                filter(Year >= 2000) 
for (row in 1:nrow(nba_performance)) {
  
  if (nba_performance[row, "Team"] == "Nets") {
   nba_performance[row, "Team"] <- "BRK"
 }
  
  if (nba_performance[row, "Team"] == "Thunder") {
   nba_performance[row, "Team"] <- "OKC"
 }
  
  if (nba_performance[row, "Team"] == "Pelicans") {
   nba_performance[row, "Team"] <- "NOP"
 }
  
  if (nba_performance[row, "Team"] == "Grizzlies") {
   nba_performance[row, "Team"] <- "MEM"
 }
  
  if (nba_performance[row, "Team"] == "Magic") {
   nba_performance[row, "Team"] <- "ORL"
 }
  
  if (nba_performance[row, "Team"] == "Clippers") {
   nba_performance[row, "Team"] <- "LAC"
 }
  
  if (nba_performance[row, "Team"] == "Rockets") {
   nba_performance[row, "Team"] <- "HOU"
 }
  
  if (nba_performance[row, "Team"] == "Suns") {
   nba_performance[row, "Team"] <- "PHO"
 }
  
  if (nba_performance[row, "Team"] == "Trail Blazers") {
   nba_performance[row, "Team"] <- "POR"
 }
  
  if (nba_performance[row, "Team"] == "76ers") {
   nba_performance[row, "Team"] <- "PHI"
 }
  
  if (nba_performance[row, "Team"] == "Kings") {
   nba_performance[row, "Team"] <- "SAC"
 }
  
  
  if (nba_performance[row, "Team"] == "Wizards") {
   nba_performance[row, "Team"] <- "WAS"
 }
  
  if (nba_performance[row, "Team"] == "Jazz") {
   nba_performance[row, "Team"] <- "UTA"
 }
  
  if (nba_performance[row, "Team"] == "Nuggets") {
   nba_performance[row, "Team"] <- "DEN"
 }
  
  if (nba_performance[row, "Team"] == "Hawks") {
   nba_performance[row, "Team"] <- "ATL"
  }
  
  if (nba_performance[row, "Team"] == "Pacers") {
   nba_performance[row, "Team"] <- "IND"
 }
  
  if (nba_performance[row, "Team"] == "Bulls") {
   nba_performance[row, "Team"] <- "CHI"
 }
  
  if (nba_performance[row, "Team"] == "Hornets" || nba_performance[row, "Team"] == "Bobcats") {
   nba_performance[row, "Team"] <- "CHH"
 }
  
  if (nba_performance[row, "Team"] == "Bucks") {
   nba_performance[row, "Team"] <- "MIL"
 }
  
  if (nba_performance[row, "Team"] == "Raptors") {
   nba_performance[row, "Team"] <- "TOR"
 }
  
  if (nba_performance[row, "Team"] == "Timberwolves") {
   nba_performance[row, "Team"] <- "MIN"
 }
  
  if (nba_performance[row, "Team"] == "Knicks") {
   nba_performance[row, "Team"] <- "NYK"
 }
  
   if (nba_performance[row, "Team"] == "Supersonics") {
   nba_performance[row, "Team"] <- "SEA"
 }
  
 if (nba_performance[row, "Team"] == "Lakers") {
   nba_performance[row, "Team"] <- "LAL"
 }
  
  if (nba_performance[row, "Team"] == "Warriors") {
   nba_performance[row, "Team"] <- "GSW"
  }
  
  if ( nba_performance[row, "Team"] == "Cavaliers") {
   nba_performance[row, "Team"] <- "CLE"
  }
  
  if (nba_performance[row, "Team"] == "Spurs") {
   nba_performance[row, "Team"] <- "SAS"
  }
  
  
  if ( nba_performance[row, "Team"] == "Heat") {
   nba_performance[row, "Team"] <- "MIA"
  }
  
  if (nba_performance[row, "Team"] == "Mavericks") {
   nba_performance[row, "Team"] <- "DAL"
  }
  
  if (nba_performance[row, "Team"] == "Celtics") {
   nba_performance[row, "Team"] <- "BOS"
  }
  
  if (nba_performance[row, "Team"] == "Pistons") {
   nba_performance[row, "Team"] <- "DET"
  }
  
}
distinct(nba_performance, Team)
nba_performance
```




```{r nba_champs, include=TRUE}
nba_champs <- select(nba_finals_mvp, 1, 5) %>%
                filter(Year >= 2000) %>%
                arrange(desc(Year))
nba_champs
```


```{r nba_seasons_offense, include=TRUE}
nba_seasons_offense <- select(nba_seasons1, Year, Tm, Player, Offense=Offense_1, Defense = Defense_1)
nba_seasons_offense
nba_seasons_offense %>%
  arrange(desc(Offense)) %>%
  slice(1:100)
```


```{r offense, include=TRUE}
offense <- nba_seasons_offense %>%
              filter(Year >= 2000) %>%
              group_by(Year, Tm) %>%
              summarize(mean_offense=sum(Offense), mean_defense=sum(Defense))
offense <- offense %>%
            arrange(desc(mean_offense))
offense
```

```{r change_names, include=TRUE}
offense %>%
  arrange(desc(Year)) 
```

```{r year_avg, include=TRUE}
year_avg <- offense%>%
              group_by(Year)%>%
              summarize(league_avg_offense=mean(mean_offense), league_avg_defense=mean(mean_defense))
year_avg
```

```{r offense_champs, include=TRUE}
offense_champs <- left_join(nba_champs, offense, by=c("Year"="Year", "NBA Champion"="Tm"))
offense_champs <- offense_champs %>%
                    filter(mean_offense > -100000)
offense_champs<-rename(offense_champs, champ="NBA Champion")
offense_champs
```


```{r plot_offense, include=TRUE}
offense_champs %>%
  ggplot(mapping=aes(x=champ, y=mean_offense, color="red", width=0.5)) +
    geom_bar(stat="identity")
par(mar=c(11,4,4,4))
test2 <- rbind(offense_champs$mean_offense,offense_champs$mean_defense, year_avg$league_avg_offense, year_avg$league_avg_defense)
barplot(test2,beside=T, names.arg = offense_champs$champ, las=2, legend = T)
legend("right", 
       legend = c("Mean Offense", "Mean Defense", "League avg Offense", "League avg Defense"), 
       fill = c("grey", "dimgrey", "red", "blue"),
       bty = "n",
       cex = 0.5)
```



```{r performances}
performances <- nba_performance
payroll_df <- select(nba_seasons1, Year, Tm, Player, TrueSalary)
payroll_df$TrueSalary <- sub('.', '', payroll_df$TrueSalary) %>% as.numeric()
payroll_df
payroll_df <- payroll_df %>% filter(Year >= 2000) %>% 
  arrange(Year) %>% 
  group_by(Year, Tm) %>% 
  mutate(payroll=sum(TrueSalary))
payroll_df
  
performances <- performances %>% select(Year, Team, `Winning Percentage`) %>% arrange(Year)
performances$Year <- substr(performances$Year, 1, 4) %>% as.numeric()
performances
```



```{r payroll}

payroll_df <- read_csv("NBA_Season_Data.csv")
payroll_df$TrueSalary <- as.numeric(gsub("[$,]", "", payroll_df$TrueSalary))

payroll_df <- payroll_df %>% filter(!is.na(TrueSalary))


payroll_df <- payroll_df %>% filter(Year >= 2000) %>% 
  group_by(Tm, Year) %>% 
  mutate(payroll=sum(TrueSalary))

payroll_df %>% select(Tm, Year, payroll)

```
